### PR TITLE
fix tests using bad folder name 'Resources'

### PR DESCRIPTION
**Pull request by eljeff**
fix for https://github.com/AudioKit/AudioKit/issues/2460
You can't use a folder called 'Resources'

### CODE REVIEW

**Comment by aure** [comment]
Do you have a reference as to why Resources is a bad folder name? Never had a problem with that folder name on my local machine or CI.

**Comment by eljeff** [comment]
I don't have any references beyond googling the stuff I mention in the issue, specifically 'bundle format unrecognized, invalid, or unsuitable'.

Simple fix though

**Comment by aure** [comment]
It had nothing to do with the folder name so I am going to close this "fix"

**Comment by eljeff** [comment]
It's a fine alternative to remove reference to the exact folder that was causing the issue, so I wouldn't say it has 'nothing to do with it'.

Did you just leave the files in there anyway? Are they used?

Renaming the folder fixed it for me, so I bet it will fix it for someone else when they encounter this same problem.

**Comment by aure** [comment]
They are resources we could use and they're in the repo already so I don't want to remove them for now. Renaming the folder was just coincidentally a fix. Whatever that folder is named, if it is added to the resources in Package.swift as a .copy reference, will not work. The name was not the issue.

**Comment by eljeff** [comment]
`Whatever that folder is named, if it is added to the resources in Package.swift as a .copy reference, will not work. The name was not the issue.`
I added it via copy reference using a different name though, and it worked fine.
I'm happy w/ the fix you've done, I just want to include as much info as possible.

**Comment by eljeff** [comment]
If it just works w/out the copy reference in the package, and you can still access those files, that is def a cleaner fix.

**Comment by aure** [comment]
I'm fine either way too.

**Comment by eljeff** [comment]
Are the files still accessible w/out the copy reference?

**Comment by aure** [comment]
I don't know, since they aren't used 🤷

**Comment by eljeff** [comment]
Well then yea either keep this fix or inscribe in the dark arcanum of audiokit lore that you can't have a folder named Resources in your copy reference in a swift package. 🧙‍♀️

**Comment by eljeff** [comment]
Muchas gracias!

**Pull request merged**
