### PR TITLE
V4 develop - Issue #2073

### PR DESCRIPTION
**Pull request by ryanfrancesconi**
Issue #2073 
AKPlayer.load() update for v4 interim fix.

### CODE REVIEW

**Comment by aure** [comment]
I'll fix the problems this raises in iOS

**Comment by ryanfrancesconi** [comment]
oh i just saw that and fixed it

**Comment by aure** [comment]
thanks

**Comment by ryanfrancesconi** [comment]
finally.

**Comment by ghubaddole** [comment]
Thanks a ton!

**Pull request merged**
