### PR TITLE
more direct setting of hidden params in decimator

### PR DESCRIPTION
**Pull request by eljeff**
simpler way to set values.
aure did this.

updated test.

### CODE REVIEW

**Comment by eljeff** [comment]
since this hasnt been merged yet, now it also uses correct values for some distortion parameters

**Comment by aure** [comment]
I'll take your word for it, but just so I know, where did you get the new info for the parameter limits and defaults from?

**Comment by eljeff** [comment]
> I'll take your word for it, but just so I know, where did you get the new info for the parameter limits and defaults from?

The documentation
Right click on the property name, jump to definition.

**Comment by aure** [comment]
> > I'll take your word for it, but just so I know, where did you get the new info for the parameter limits and defaults from?
> 
> The documentation
> Right click on the property name, jump to definition.

ruh roh, lets talk about it on slack

**Pull request merged**
