### PR TITLE
silenced deprecation warnings

### PR DESCRIPTION
**Pull request by mlostekk**

### CODE REVIEW

**Review by aure — APPROVED** [review]

**Comment by NickCulbertson** [comment]
I see where assign is deprecated. I'm not sure why `.update` is throwing an error. https://developer.apple.com/documentation/swift/unsafemutablepointer

**Comment by mlostekk** [comment]
Oh, darn. Maybe its not backwards compatible. Which targetSDK are you compiling for?

**Comment by aure** [comment]
I guess we can revert this change.

**Comment by NickCulbertson** [comment]
Updating Xcode fixed it. Unfortunately, I'm not sure what version I was on previously. I think it was Xcode Version 14.1

**Comment by mlostekk** [comment]
Revert PR opened [here](https://github.com/AudioKit/AudioKit/pull/2843). The [documentation](https://developer.apple.com/documentation/swift/unsafemutablepointer/assign(from:count:)?changes=latest_minor) is not very clear so lets revert to keep backward compat.

**Pull request merged**
