### PR TITLE
AVLazyTap

### PR DESCRIPTION
**Pull request by dave234**
Moved TPCircularBuffer to new Internals/Utitlies directory.
Added TPCircularBuffer+AudioBufferList as AVLazyTap depends on it.
Used the newest version of TPCircularBuffer, had to make some changes as it had using std in the header and it was stomping on atomic_int.

### CODE REVIEW

**Comment by megastep** [comment]
Shouldn't this be added to the tvOS project as well?

**Comment by dave234** [comment]
@megastep  I have pretty much neglected tvOS.  What's the status on AVAudioEngine?  Does it all work?

**Comment by megastep** [comment]
@dave234 Yeah it's pretty much on par with iOS, with very few exceptions.

**Comment by dave234** [comment]
@megastep Ok, it's in there.  Moving forward I guess I'll just test on the simulator.

**Comment by aure** [comment]
Passed my tests locally, hopefully Travis will be on Xcode 9beta6 soon.  Thanks once again Dave.

**Pull request merged**
