### PR TITLE
Fix FormatConverter+Compressed on iOS 18, macOS 15, tvOS 15 and VisionOS 2

### PR DESCRIPTION
**Pull request by 1998code**
Use export(to:as:) instead.

Remark: 
The old one was fully deprecated on visionOS 2 and Xcode 16. Failed to fallback.
As a workaround, I used ```#if !os(visionOS)...``` to prevent crashes.
Screenshot 2024-06-24 at 2 15 14 PM

Ref Doc:
https://developer.apple.com/documentation/avfoundation/avassetexportsession/4354409-export

### CODE REVIEW

**Comment by 1998code** [comment]
Link to issue: https://github.com/AudioKit/AudioKit/issues/2921

**Comment by 1998code** [comment]
@aure / @wtholliday Please help review this PR. Thanks.

**Comment by warpling** [comment]
Bump :)
Thanks for doing this @1998code!

**Comment by 1998code** [comment]
Welcome @warpling 
I only tested on visionOS 2.0 beta.

**Review by Matt54 — CHANGES_REQUESTED** [review]

**Comment by Matt54** [comment]
I think a good stop gap solution here would be to hide the existing method from visionOS and then create a new method that works across all platforms using the modern concurrency version of AVAssetExportSession's export. This way we don't break the current api.

**Pull request closed without merging**
