### PR TITLE
Allow more precise control of audio session bluetooth options

### PR DESCRIPTION
**Pull request by pcbeard**
This addresses the comment I made in issue #675.

### CODE REVIEW

**Comment by aure** [comment]
I think you're right about the manner of this solution, but I am not a big fan of the name "useBluetoothOptions" because that implies that the var is a Boolean.  I'd just change it to "bluetoothOptions". I can do that after accepting the pull request or you can make the edit if you agree.  Thanks!

**Comment by pcbeard** [comment]
OK, I made the change.

**Comment by pcbeard** [comment]
This should fix the travis build, since AVAudioSessionCategoryOptions isn't available on macOS.

**Comment by aure** [comment]
Cool!

**Pull request merged**
