### PR TITLE
AKAudioPlayer in reverse

### PR DESCRIPTION
**Pull request by ryanfrancesconi**
Hey Guys,

I added reverse playback to AKAudioPlayer as it is something that I need. I tried all of the various reverse functions in AKAudioFile - but none of them worked for me. They just created empty data. I'm unsure if this is a new issue or an old one, but it's something to check. I'll open an issue for that. In the meantime, what I really wanted was just to be able to flip the internal buffer around without having to make a new AKAudioFile -- so that's this update here!

Ryan

### CODE REVIEW

**Comment by aure** [comment]
We have some build issues but they are not related to your changes.

**Comment by aure** [comment]
But I am quite concerned with the number of changed files listed.  Seems like every file got touched, including all the images?  I worry that this pull request might increase the size of the repo unnecessarily.

**Comment by aure** [comment]
Do you think you could check out a fresh copy of AudioKit and just make the changes from 	a9dd5fe ?

**Comment by ryanfrancesconi** [comment]
yeah totally. let me do that. I actually didn't realize that git was going to do what it in the pull request / commit.
 
I had just copied my repo to a new computer and that's what happened.
 
 
-----Original Message-----

**Pull request closed without merging**
