### PR TITLE
Buffer and mixed sample rate player tests

### PR DESCRIPTION
**Pull request by ryanfrancesconi**
For issue in PR: https://github.com/AudioKit/AudioKit/pull/2489

This completes what he started

### CODE REVIEW

**Comment by aure** [comment]
Do you think 12345.wav could be converted to 48K by FileConverter on the fly instead of including it as a resource asset to AudioKit?

**Comment by ryanfrancesconi** [comment]
it certainly could. i can do that

**Comment by aure** [comment]
You might have to make a new branch off of develop in order to keep the 48K Version of the file from entering the git history.

**Comment by ryanfrancesconi** [comment]
how's that?

**Comment by ryanfrancesconi** [comment]
> You might have to make a new branch off of develop in order to keep the 48K Version of the file from entering the git history.

is that really so important? i deleted the file

**Pull request closed without merging**
