### PR TITLE
added echo cancellation to EZMicrophone & AKSettings

### PR DESCRIPTION
**Pull request by mlostekk**
Hi,

i was thinking if this would not solve the requirement for echo cancellation? This is the only flag that actually has to be set

It would also resolve this request. (and we are planning to use echo cancelation with AK too)

https://github.com/AudioKit/AudioKit/issues/1319

### CODE REVIEW

**Comment by aure** [comment]
Cool, I hope this helps you and others out.

**Comment by mlostekk** [comment]
@aure do you have examples out there to use EZMicrophone in a swift based project?

**Comment by aure** [comment]
@mlostekk Other than how we use it in AK?

**Comment by mlostekk** [comment]
Well, i see that it can simply be created and then its already running. it does does not have to be attached to AudioKit as AKNode. So my case is solved. But anyhow, how do you attach those `EZxxx` devices as they are not a `AKNode`s?

**Comment by aure** [comment]
The AKMicrophoneTrackerEngine uses the EZMicrophone directly.  Also, AudioKit uses EZAudioDevice optionally for device management. AudioKit never meant to wrap all of EZAudio's capabilities, but we do make use of it and we embed it in AudioKit for those reasons.

**Comment by mlostekk** [comment]
okay, thanks for the clarification

**Pull request merged**
