### PR TITLE
Generated AKAntiresonator class 

### PR DESCRIPTION
**Pull request by dclelland**
Based on areson opcode, see: http://www.csounds.com/manual/html/areson.html

### CODE REVIEW

**Comment by dclelland** [comment]
Whoops, forgot to import into AKFoundation.h, will do that in a second

**Comment by megastep** [comment]
This is still failing to compile in Travis...

**Comment by dclelland** [comment]
huh, I'll have to take a look tonight...

**Comment by narner** [comment]
Thanks for adding this @dclelland, I'm looking forward to hearing how it sounds!

**Pull request merged**
