### PR TITLE
Ported the core code to compile and link successfully on both Android…

### PR DESCRIPTION
**Pull request by sseyod**
Ported the core code to compile and link successfully on both Android and Windows

All the .c code can be now be compiled as C++17
It was necessary to rename some files (STK/Envelope -> STK/STKEnvelope, and the ugens file) as otherwise on Windows you get errors of the form:
>>>
...warning MSB8027: Two or more files with the name of fir.cpp will produce outputs to the same location.
This can lead to an incorrect build result.  The files involved are:
....AudioKitCore\Synth\Envelope.cpp, ...Sources\STK\Envelope.cpp
<<<

### CODE REVIEW

**Comment by sseyod** [comment]
Hi! This is my first ever attempt to create a Pull Request on GitHub. I hope I've done everything correctly! Pete

**Comment by aure** [comment]
This pull request should be made off the v5-develop branch. It also has some failing tests. But its cool if you can make those changes.

**Comment by sseyod** [comment]
Many thanks - I'll get back to my porting efforts and try again soon :)

Best wishes,

Pete

**Comment by sseyod** [comment]
Hi @aure I've posted a question on how to run the unit tests here:
https://stackoverflow.com/questions/65953380/how-to-run-the-audiokit-unit-tests
Hopefully you might be able to answer the question there! Many thanks, Pete

**Pull request closed without merging**
