### PR TITLE
Fix for Xcode 12.4 failing to build

### PR DESCRIPTION
**Pull request by orchetect**
Fix for Xcode 12.4 failing to build.

Related issue: #2656

### CODE REVIEW

**Comment by aure** [comment]
Normally we do our PRs off of develop branch but I'll make an exception since they are both in sync right now.

**Comment by aure** [comment]
Tagged at 5.3.2

**Comment by orchetect** [comment]
Sorry, that wasn't intentional. Initiated the PR from the AudioKit side and didn't notice it was targeting main. Usually I initiate from my branch and it always targets develop.

**Comment by orchetect** [comment]
The first PR CI run seems to be freewheeling for some reason. Might want to manually cancel it manually: https://github.com/AudioKit/AudioKit/actions/runs/1714913244

**Pull request merged**
