### PR TITLE
Added more meta events and AKMIDITrackView

### PR DESCRIPTION
**Pull request by emurray2**
There are some more meta events I ran into parsing issues with before, so I added them into `AKMIDIMetaEventType.swift` . I am not sure what some of them are for, but they were included in some MIDI files I was using for testing. I also created a MIDI Track view which I am really excited about. It still has some bugs, but I am working on pushing another improved version soon. More details can be found in `AKMIDITrackView.swift` .

### CODE REVIEW

**Comment by aure** [comment]
Looks cool. I'd love to see an example project added to the Examples directory (catalyst compatible if possible!).

**Comment by emurray2** [comment]
Thank you! Yeah, I’ll see if I can make that happen :) !

**Comment by aure** [comment]
Have you added these files to the AudioKit projects?

**Comment by emurray2** [comment]
Yes, I believe I added them to the iOS development project. Is there anywhere else I should add them?

**Comment by emurray2** [comment]
Wait, never mind I haven’t. I only did that for my local project I just realized. I’ll do that right now.

**Comment by aure** [comment]
There are a lot of forced unwrappings and other small things like stray spaces in your code. I just pushed up a bunch of fixes. Do you have SwiftLint on your system?

**Comment by emurray2** [comment]
Yeah I noticed that when I submitted my pull request yesterday. I just installed SwiftLint, and now I see the warnings which is very helpful. Thank you!

**Pull request merged**
