### PR TITLE
AKTimeSignature and reading time signature events from MIDI file (re issue: #1353, PR #1354)

### PR DESCRIPTION
**Pull request by crashingbooth**
re https://github.com/AudioKit/AudioKit/issues/1353 and https://github.com/AudioKit/AudioKit/pull/1354
These changes provide a way to read all the time signatures events from a MIDI file, and get the relevant time signature event for a given position.  Time signature events for current position can be read accurately even if the event is at time stamp 0.0  and current position is 0.0.

- added struct ```AKTimeSignature```
- added ```allTimeSignatureEvents``` and ```getTimeSignature(at: )``` to ```AKSequencer```
- modified ```addTimeSignatureEvent``` to use ```AKTimeSignature```, to include the timeStamp for the event as an argument, and to have a flag for clearing existing events
- modified ```AKSequencer```'s ```removeTracks``` to explicitly clear tempo and time signature events
- added time signature tests to AKSequencerTests file
- updated MIDIFileEditAndSync example for modified ```addTimeSignatureEvent``` method

### CODE REVIEW

**Comment by aure** [comment]
I think you need to commit changes to the project files to include AKTimeSignature.swift.

**Comment by crashingbooth** [comment]
I thought that I did: https://github.com/AudioKit/AudioKit/pull/1372/commits/5453bc4ea3e3c82504805275b2818cd020b6d8e1

**Comment by crashingbooth** [comment]
I think I see what you mean

**Comment by aure** [comment]
Cool!

**Comment by mahal** [comment]
Thanks @crashingbooth for making this happen!

**Pull request merged**
