### PR TITLE
Help with Xcode < 6.3

### PR DESCRIPTION
**Pull request by megastep**
New `AKCompatibility.h` with a set of macros to allow compilation with older versions of Xcode. This should help with Travis CI.

### CODE REVIEW

**Comment by megastep** [comment]
It's compiling now but failing when trying to run the test.

**Comment by megastep** [comment]
This is gonna be a problem:

```
2015-04-19 04:16:14.229 Math[953:2b03] AuHAL Module: found 0 input device(s):
2015-04-19 04:16:14.231 Math[953:2b03] selected input device: (null) 
```

**Comment by megastep** [comment]
I'm gonna make further changes so that it uses the dummy driver when running within Travis CI. Should at least avoid these crashes.

**Comment by aure** [comment]
I'll keep this pull request open for now.

**Comment by aure** [comment]
Let's not worry about the test, just the compilation.  I'm changing the way tests are done.

**Comment by aure** [comment]
I uploaded a simple test project that uses XCTest and updated the Travis YML file, so if you merge those changes, it should build once the dummy driver is in place, I hope.

**Pull request merged**
