### PR TITLE
Balancer problem, making a PR to see if the issue happens on CI and other people's machines

### PR DESCRIPTION
**Pull request by aure**
This simple change, similar to ones that worked this morning, breaks AudioKit.h. Why?

### CODE REVIEW

**Comment by megastep** [comment]
Well I see that it fails to compile because of unknown references. Maybe it has something to do with Taylor's recent changes to make internal APIs less accessible?

**Comment by aure** [comment]
> Well I see that it fails to compile because of unknown references. Maybe it has something to do with Taylor's recent changes to make internal APIs less accessible?

No I don't think. I did this to 50 or 60 nodes in a previous commit without issue.

**Comment by aure** [comment]
I see the issue now. The balancer hpp file was the last place that AKSoundpipeDSPBase.hpp was imported from a public header file.

**Comment by aure** [comment]
I've made the AKSoundpipeDSP.hpp file into a .hpp/.mm pair but still having some issues.

**Pull request merged**
