### PR TITLE
Adding rate functionality for MusicPlayer based sequencers

### PR DESCRIPTION
**Pull request by JSMilton**

### CODE REVIEW

**Comment by aure** [comment]
This change breaks the SamplerDemo project.  Looks like the SamplerDemo example could be updated relatively easily to use setRate instead, but I kind of like use properties if possible.

**Comment by JSMilton** [comment]
Ah ok, I'll update to use the property setter. The reason I didn't was because there are other properties, such as tempo and length, that have a separate method for the setter so I thought that was the style you guys were going for.

**Comment by aure** [comment]
If that's the style, you can leave it as you did it and update the example project.  I guess we have evolved a bit since then but haven't updated this code.

**Comment by aure** [comment]
If you wanted to make everything property setters, I'm not going to complain, but that would be a separate pull request I guess.

**Comment by JSMilton** [comment]
I'll probably just update the Demo for now, then I'll make a separate PR if I get round to refactoring the property setters. Cheers!

**Pull request merged**
