### PR TITLE
Develop3

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by aure** [comment]
I'm sorry, but Apple is inconsistent in the way they use both dry wet mix and wet dry mix, but in AudioKit we always use dry wet mix in that order because dry is 0 and wet is 1.  I like the other changes but you'll have to make everything else you changed back to dry wet.

**Comment by aure** [comment]
Also, you committed a change to the playgrounds making the synthesis ones "macOS" and they should start off as "iOS" not a big deal, but worth mentioning.

**Comment by aure** [comment]
Apple has in AUReverb2: kReverb2Param_DryWetMix and even though they might be moving to a wetDryMix standard in their Swift interface, I think that's fundamentally wrong and a direction I don't want AudioKit to take.

**Comment by adamnemecek** [comment]
Fair enough lol. You make solid points.

**Comment by aure** [comment]
Lastly, its such a commonly used node that changing the name is a bigger deal than most name changes (even the examples are breaking).

**Comment by aure** [comment]
Can you please remake the good changes in this pull request?

**Pull request closed without merging**
