### PR TITLE
Easy exponential curves

### PR DESCRIPTION
**Pull request by adambmedia**
Added FunctionTable for exponential curves with tunable positive and negative second order derivatives yielding concave up and down curves with varying degrees of bend.

### CODE REVIEW

**Comment by aure** [comment]
Reviewing this now.  AKPhasingControl was removed from AudioKit because AKPhasor can be used at k-rate without issue as part of rate agnosticism.  I don't think its needed.  Please rename AKExponentialCurvesVariableGrowth toe AKVariableGrowthExponentialCurves.

**Comment by adambmedia** [comment]
I couldn’t use AKPhasor as the index argument in AKTableValueControl as follows:

AKTableValueControl *tableRead;
tableRead = [[AKTableValueControl alloc] initWithFunctionTable:myTable atIndex:myPhasorControl];

-adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 3:50:31 PM, Aurelius Prochazka (notifications@github.com) wrote:

Reviewing this now. AKPhasingControl was removed from AudioKit because AKPhasor can be used at k-rate without issue as part of rate agnosticism. I don't think its needed. Please rename AKExponentialCurvesVariableGrowth toe AKVariableGrowthExponentialCurves.

**Comment by adambmedia** [comment]
Don’t you think AKVariableGrowthExponentialCurves is inferior in terms of autocomplete?  I’m reaching for an exponential curve not a variable growth.
-adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 3:50:31 PM, Aurelius Prochazka (notifications@github.com) wrote:

Reviewing this now. AKPhasingControl was removed from AudioKit because AKPhasor can be used at k-rate without issue as part of rate agnosticism. I don't think its needed. Please rename AKExponentialCurvesVariableGrowth toe AKVariableGrowthExponentialCurves.

**Comment by aure** [comment]
Do you need to have "VariableGrowth" in these names at all, why not just AKExponentialCurves?

**Comment by adambmedia** [comment]
Hmmm, there is a better name here but not VariableGrowth.  I needed something where I could customize the second order derivative of an otherwise exponential curve.  The existing exponential curves where insufficient.  It’s the difference between GEN 16 and 25 and its a big difference.
-adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 3:57:14 PM, Aurelius Prochazka (notifications@github.com) wrote:

Do you need to have "VariableGrowth" in these names at all, why not just AKExponentialCurves?

**Comment by aure** [comment]
AudioKit has human readable class  names not alphabetical ones. Otherwise we'd be naming things AKEnvelopeLinear instead of AKLinearEnvelope, etc.

**Comment by aure** [comment]
Because things are different numbered GENs in Csound don't necessitate that they have to exist in AudioKit that way.  If you're building exponential curves with different methods, that's great, the end result is what we're naming, not the method by which we get there.

**Comment by adambmedia** [comment]
I know what audiokit has.  God dammit Aure.  A Linear Envelope makes sense as a thing because its concise and is readable.  When we’re talking about similar classes with nuanced mathematical differences, that rationale falls apart.  The result is that you’re constantly checking he docs because autocomplete fails you.  For instance, the thought process when designing sound is
1. I know what kind of function I want, it’s an exponential curve where I can control the bend
2. is that, growth, derivative, inflection point, gah, all are equally appropriate, which ones did audiokit choose
3. google or look at the documentation

Better is, I type expon... and tab through the possibilities.  Actually, this way, I may discover alternatives.

Makes sense, no? -adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 3:57:14 PM, Aurelius Prochazka (notifications@github.com) wrote:

Do you need to have "VariableGrowth" in these names at all, why not just AKExponentialCurves?

**Comment by adambmedia** [comment]
You would still argue that it is human readable. -adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 4:02:14 PM, Aurelius Prochazka (notifications@github.com) wrote:

AudioKit has human readable class names not alphabetical ones. Otherwise we'd be naming things AKEnvelopeLinear instead of AKLinearEnvelope, etc.

**Comment by adambmedia** [comment]
Totally makes sense. I’m naming to describe what the thing does and how it would be imagined by someone wanting to use it and looking for it. Where do you see a historical reference to GEN routine naming, which is just a number, no? -adam

--
Adam Boulanger
co-founder, Hear For Yourself
t. 617-990-2704
e. adam@hearforyourself.com
w. www.adamboulanger.com

On January 21, 2015 at 3:57:14 PM, Aurelius Prochazka (notifications@github.com) wrote:

Do you need to have "VariableGrowth" in these names at all, why not just AKExponentialCurves?

**Comment by adambmedia** [comment]
Variable growth does make the most sense.

**Comment by aure** [comment]
You introduced AKPhasorControl because AKTableValueControl had not been made rate-agnostic yet.  I fixed that so now your example should work with AKPhasor.   Thanks for finding that.   Please remove AKPhasorControl from this pull request.  I don't think my request that you change the name of the variable growth exponential curves was unreasonable either.  But, now after reviewing it further, this function table closely parallels AKSegmentArray which can be linear or curved.  I propose lumping all of these into one nice AKSegments function table which can handle linear or variable growth curves.

**Pull request closed without merging**
