### PR TITLE
Added StruckMetalBar, Vibes, and BowedString presets

### PR DESCRIPTION
**Pull request by narner**

### CODE REVIEW

**Comment by aure** [comment]
This isn't passing travis.  Maybe while you're at it, shipHorn is probably more well known as a Foghorn.

**Comment by narner** [comment]
Typo, fixing now.

**Comment by aure** [comment]
Don't forget that you can run Tests/travis.sh locally to quickly check whether your changes will pass Travis.

**Comment by narner** [comment]
Ah yes, of course!
I'm thinking it may be worthwhile to add a small section for that on either the FAQ, or a small Tutorial page showing how to check your changes before committing them. I'll add that as a Trello card.

**Comment by aure** [comment]
You already made a web page for contributing.  I just updated it with the Run Tests part of the workflow:
http://audiokit.io/tutorials/contributing

**Pull request merged**
