### PR TITLE
Adding resonant filter to AudioKit

### PR DESCRIPTION
**Pull request by dclelland**
See issue #453 

So far I've added a `resonantFilter.swift` file (I may do an `AKResonantFilter` `AKNode` subclass to complement it but for now I just want to use it with computed parameters) and added it (along with `reson.c`, thanks @aure for [updating Soundpipe](https://github.com/audiokit/AudioKit/commit/dfa5e76242321a7e11301f126c24920e1ee84785) 😀) to the OS X/iOS/tvOS projects.

Haven't tested this yet but thought it better to share early so I can get on the right track :)

Two questions:

- To get this working, do I need to make sure `reson` exists within Sporth?
- Once ready, are there any tests I should write?

### CODE REVIEW

**Comment by dclelland** [comment]
Also, I remember, the [Csound `reson` opcode](http://www.csounds.com/manual/html/reson.html) had an `iscl` flag which we needed to tweak a bit in order to get it working right in AudioKit 2 (we set it to `1`), I see that [included in the `sp_reson` struct](https://github.com/audiokit/AudioKit/blob/develop/AudioKit/Common/Internals/Soundpipe/soundpipe.h#L1144), will we need some kind of special handling for that here?

(Still trying to understand how all this ties together...)

**Comment by dclelland** [comment]
I'm also having trouble installing AudioKit locally so I can test things out. Usually I'll have my project in a directory next to my AudioKit fork, and install by adding a line like `pod 'AudioKit', path: '../AudioKit-fork'` to my podfile and it gets installed as a Development Pod, but nothing shows up in my Xcode project. I've run `build_frameworks.sh` but still nothing. Am I overthinking this?

**Comment by aure** [comment]
This won't work without the sporth version of reson installed into AudioKit.  It looks like Paul added it back to Sporth, so it means just copying some stuff over and changing some lines of code.  If you add me as a collaborator on your fork, I can push these changes to it so this all can live on one pull request.

**Comment by dclelland** [comment]
Cool, just sent you an invite.

It's likely that this particular component won't work 'out of the box' - is there a way I can install AudioKit as a development pod somehow? I don't really want to have to spend ten minutes recompiling the whole framework every time I do a build...

**Comment by aure** [comment]
You can't do framework development with CocoaPods.  I develop using playgrounds and I don't compile everything when I make any change.  Xcode does a pretty good job of knowing what needs to be recompiled.  I'll get this reson project jumpstarted for you.

**Comment by dclelland** [comment]
Cheers buddy.

PS I was able to get it working by:

1. Dragging the `AudioKit for iOS` project into my own project
2. Building the `AudioKit-iOS` framework
3. Dragging `AudioKit.framework` into the Link Binary With Libraries build phase in my own project

Now Xcode is smart enough that if I change something in AudioKit, it will only recompile what it has to. I can drop breakpoints in AudioKit code, alt+clicking on keywords takes me to implementations, it's all working good.

Easy!

**Comment by dclelland** [comment]
Looks good but... does this contain the reson Sporth integration?

**Comment by aure** [comment]
This should be good to go.  If you make any other tweaks, just make a new pull request.

**Pull request merged**
