### PR TITLE
AudioPlayer: Added Seek and Time Keeping

### PR DESCRIPTION
**Pull request by Matt54**
Added ability to seek the audio player as well as get the current time in the audio file of the player even after it seeks or pauses.

### CODE REVIEW

**Comment by aure** [comment]
How about two tests for the new additions?

**Comment by warpling** [comment]
Should stoppedTime be pausedTime since stopping seeks to 0 as far as I understand.

**Comment by Matt54** [comment]
@warpling - I agree with the rename
@aure - I added some tests

**Comment by royherma** [comment]
@aure So we have seeking available now?! 🙏

**Pull request merged**
