### PR TITLE
Modify knobs & sliders custom controls to appear in IB / Thanks to Aure!

### PR DESCRIPTION
**Pull request by swiftcodex**

### CODE REVIEW

**Comment by aure** [comment]
Not sure why Travis wasn't passing, but I don't think there's anything wrong with this code.  Release the hounds.

**Comment by aure** [comment]
I do agree with the hound that variable names like knob120_indicator are highly non-Swifty.

**Comment by swiftcodex** [comment]
Super non-swifty. Agreed. It should probably be smallKnobIndicator

**Comment by swiftcodex** [comment]
I wonder who created those property names? ;)

**Pull request merged**
