### PR TITLE
AKMicrophone.init() crash on iPhone 6

### PR DESCRIPTION
**Pull request by VAndrJ**
Problem:
AKMicrophone.init() cause crash on iPhone 6 because in method:
 ```
private func getFormatForDevice() -> AVAudioFormat? {
    #if os(iOS) && !targetEnvironment(simulator)
    let currentFormat = AudioKit.engine.inputNode.inputFormat(forBus: 0)
    let desiredFS = AudioKit.deviceSampleRate
    return AVAudioFormat(commonFormat: currentFormat.commonFormat,
                         sampleRate: desiredFS,
                         interleaved: currentFormat.isInterleaved,
                         channelLayout: currentFormat.channelLayout!)
    #else
    let desiredFS = AKSettings.sampleRate
    return AVAudioFormat(standardFormatWithSampleRate: desiredFS, channels: 2)
    #endif
}
 ```
currentFormat.channelLayout is nil.

### CODE REVIEW

**Comment by aure** [comment]
Thanks!

**Comment by GabiGVeesto** [comment]
Hi there , I'm is still getting a lot of crashes due to the issue, downgrading to 4.5.3 seems to lower the amounts but crashes still occur, what release will contain a final fix for the issue? 

screen shot 2019-02-05 at 11 05 39

**Comment by VAndrJ** [comment]
@GabiGVeesto it seems that you faced another issue. Looks like it attempt to initialize multiple input audio units. But I could be wrong. Is something still being done before the microphone is initialized?

**Comment by GabiGVeesto** [comment]
@VAndrJ
 I have added the following code before the AKMicrophone():

AKSettings.audioInputEnabled = true
AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus:
0).sampleRate
try? AKSettings.setSession(category: .playAndRecord)

it reduced the crashes count but hasn't fixed the issue completely

**Comment by VAndrJ** [comment]
> @VAndrJ I have added the following code before the AKMicrophone(): AKSettings.audioInputEnabled = true AKSettings.sampleRate = AudioKit.engine.inputNode.inputFormat(forBus: 0).sampleRate try? AKSettings.setSession(category: .playAndRecord) it reduced the crashes count but hasn't fixed the issue completely
> […](#)

What was previous session category? 

Idea. Maybe on microphone init it is necessary to check inputNode audioUnit and uninitialize it if present?

**Comment by CooperCodeComposer** [comment]
Looks like we're experiencing the same crash on AKMicrophone.getFormatForDevice() on an iPhone 6 (and an iPad Pro). I see a fix was merged. May I ask is there any idea when an updated Cocoapod would be available? Thx!

**Comment by aure** [comment]
@CooperCodeComposer CocoaPod for AudioKit 4.6 just pushed.

**Comment by CooperCodeComposer** [comment]
@aure awesome - thank you very much!

**Pull request merged**
