### PR TITLE
Move AKCoreSynth.hpp to project scope in iOS project (#1691)

### PR DESCRIPTION
**Pull request by sparist**
Issue: #1691

### CODE REVIEW

**Comment by Shinehah-Gnolaum** [comment]
To add missing AKCoreSnth.hpp import to AudioKit.h I just added the line "#import <CoreAudioKit/AKCoreSynth.hpp>" at the top of AudioKit.h, below the line "pragma once". Is that correct?
How do I move AKCoreSynth.hpp to project scope in iOS project?
Why is this not already corrected in the current repository?

**Comment by mfk-ableton** [comment]
In https://github.com/AudioKit/AudioKit/pull/1694/commits/6dc29d359056489f2acb6caa9800042283f2f24b the header got added, in https://github.com/AudioKit/AudioKit/pull/1694/commits/2cd22844c5ae5b6a4f4ebc2e68922b1756a65721 it got removed again as well as made NOT Public. I made it public in https://github.com/AudioKit/AudioKit/pull/1708 again (should be latest release). I'm not sure why this PR got merged in the first place, in fact it seems really hard to understand why this was an issue to begin with. We could cherry-pick https://github.com/AudioKit/AudioKit/pull/1694/commits/6dc29d359056489f2acb6caa9800042283f2f24b on a separate branch and merge it back to master.

**Comment by sieren** [comment]
In 6dc29d3 the header got added, in 2cd2284 it got removed again as well as removed from the public headers in the framework. I made it public in #1708 again (should be latest release). I'm not sure why this PR got merged in the first place, in fact it seems really hard to understand why this was an issue to begin with. We could cherry-pick 6dc29d3 on a separate branch and merge it back to master.

**Comment by sieren** [comment]
@Shinehah-Gnolaum can you elaborate what the exact problem/error message is youre seeing? And which version of Swift are you using?

**Comment by Shinehah-Gnolaum** [comment]
@sieren I am using the latest version of Xcode, which uses Swift 5. I was able to fix this problem with just adding the line '#import "AKCoreSynth.hpp"' in AudioKit.h. I didn't move AKCoreSynth.hpp to project scope. I am having other problems addressed in issue 1720. I'm waiting for AudioKit to be updated to fix that problem. Thanks for your help.

**Comment by sieren** [comment]
@Shinehah-Gnolaum ah, thanks for letting us know. I've already put a PR in place which should get merged any minute 👍

**Pull request merged**
